INSERT INTO `Type`(`ID`, `Nom`, `Description`) VALUES (1, 'Randonnée', 'Rando en forêt avec les fées');
INSERT INTO `Type`(`ID`, `Nom`, `Description`) VALUES (2, 'Promenade au bord de l''eau', 'Attention ça glisse');
INSERT INTO `Type`(`ID`, `Nom`, `Description`) VALUES (3, 'AquaPoney', "Eh salut les filles, bienvenue au cours d'aquaponey !");
INSERT INTO `Race`(`ID`, `Nom`) VALUES (1, 'Appaloosa');
INSERT INTO `Race`(`ID`, `Nom`) VALUES (2, 'Shetland');
INSERT INTO `Personne`(`ID`, `Prenom`, `Nom`, `Mail`, `Telephone`, `DateNaissance`, `NbHeureActiviteMaxSemaine`, `Discriminator`, `Password`) VALUES (1, 'Eleonore', 'W', 'eleo@mail.ca', '459456123', 2121996, null, 'javabeans.Client', null);
INSERT INTO `Personne`(`ID`, `Prenom`, `Nom`, `Mail`, `Telephone`, `DateNaissance`, `NbHeureActiviteMaxSemaine`, `Discriminator`, `Password`) VALUES (2, 'Guillaume', 'B', 'guigui@mail.ca', '549456123', 212990, null, 'javabeans.Client', null);
INSERT INTO `Personne`(`ID`, `Prenom`, `Nom`, `Mail`, `Telephone`, `DateNaissance`, `NbHeureActiviteMaxSemaine`, `Discriminator`, `Password`) VALUES (3, 'Lisa', 'S', 'oney4eva@mail.ca', '789456123', 2122010, null, 'javabeans.Professeur', null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (1, 'Pré Ouest', 4, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (2, 'Pré Nord', 2, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (3, 'Pré-Jean', 4, '');
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (4, 'Manège A', 8, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (5, 'Manège B', 6, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (6, 'Forêt Secteur Ouest', 5, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (7, 'Forêt Secteur Nord', 7, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (8, 'Rivière', 6, null);
INSERT INTO `Activite`(`ID`, `LieuID`, `PersonneID`, `TypeID`, `Nom`, `Commentaire`, `Details`, `Date`, `Duree`, `Capacite`, `EstActive`) VALUES (1, 8, 3, 2, 'Promenade au bord de l''eau', '', 'RDV au centre equestre', 06072019, 5, 4, true);
INSERT INTO `Reservation`(`ID`, `Date`, `NbPersonne`, `EstActive`, `PersonneID`, `ActiviteID`) VALUES (1, 05032019, 2, true, 1, 1);
INSERT INTO `Cheval`(`ID`, `PersonneID`, `RaceID`, `Nom`, `DateNaissance`, `Description`, `Commentaire`, `NbHeureMaxSemaine`, `Taille`) VALUES (1, 2, 2, 'Crêpe', 06032015, 'Aime le sucre', 'Boiteux', 6, 160);
INSERT INTO `Cheval`(`ID`, `PersonneID`, `RaceID`, `Nom`, `DateNaissance`, `Description`, `Commentaire`, `NbHeureMaxSemaine`, `Taille`) VALUES (2, 1, 1, 'Brownie', 6032014, 'Aime les carottes', 'Aveugle', 5, 170);
INSERT INTO `Cheval`(`ID`, `PersonneID`, `RaceID`, `Nom`, `DateNaissance`, `Description`, `Commentaire`, `NbHeureMaxSemaine`, `Taille`) VALUES (3, 2, 2, 'Cookie', 06032013, 'Aime les graines', null, 15, 175);
INSERT INTO `Cheval`(`ID`, `PersonneID`, `RaceID`, `Nom`, `DateNaissance`, `Description`, `Commentaire`, `NbHeureMaxSemaine`, `Taille`) VALUES (4, 2, 1, 'Pepito', 6032012, 'Tacheté', '', 15, 165);
INSERT INTO `Cheval_Activite`(`ChevalID`, `ActiviteID`) VALUES (1, 1);
INSERT INTO `Cheval_Activite`(`ChevalID`, `ActiviteID`) VALUES (2, 1);
INSERT INTO `Cheval_Activite`(`ChevalID`, `ActiviteID`) VALUES (3, 1);
INSERT INTO race (Nom) VALUES ('Anglo-Arabe');
INSERT INTO race (Nom) VALUES ('Akhal-Teke');
INSERT INTO race (Nom) VALUES ('Andalou');
INSERT INTO race (Nom) VALUES ('Camarguais');
INSERT INTO race (Nom) VALUES ('Curly');
INSERT INTO race (Nom) VALUES ('Hackney');
INSERT INTO race (Nom) VALUES ('Hanovrien');
INSERT INTO race (Nom) VALUES ('Furioso');
INSERT INTO race (Nom) VALUES ('Hunter');
INSERT INTO race (Nom) VALUES ('Morgan');
INSERT INTO race (Nom) VALUES ('Mustang');
INSERT INTO race (Nom) VALUES ('Trotteur');

