INSERT INTO `Type`(`ID`, `Nom`, `Description`) VALUES (1, 'Randonnée', 'Rando en forêt avec les fées');
INSERT INTO `Type`(`ID`, `Nom`, `Description`) VALUES (2, 'Promenade au bord de l''eau', 'Attention ça glisse');
INSERT INTO `Type`(`ID`, `Nom`, `Description`) VALUES (3, 'AquaPoney', "Eh salut les filles, bienvenue au cours d'aquaponey !");
INSERT INTO `Type`(`ID`, `Nom`, `Description`) VALUES (4, 'Cours galop', "Cours pour passer les galops");
INSERT INTO `Race`(`ID`, `Nom`) VALUES (1, 'Appaloosa');
INSERT INTO `Race`(`ID`, `Nom`) VALUES (2, 'Shetland');
INSERT INTO `Race`(`ID`, `Nom`) VALUES (3, 'Curly');
INSERT INTO race (Nom) VALUES ('Akhal-Teke');
INSERT INTO race (Nom) VALUES ('Andalou');
INSERT INTO race (Nom) VALUES ('Camarguais');
INSERT INTO race (Nom) VALUES ('Anglo-Arabe');
INSERT INTO race (Nom) VALUES ('Hackney');
INSERT INTO race (Nom) VALUES ('Hanovrien');
INSERT INTO race (Nom) VALUES ('Furioso');
INSERT INTO race (Nom) VALUES ('Hunter');
INSERT INTO race (Nom) VALUES ('Morgan');
INSERT INTO race (Nom) VALUES ('Mustang');
INSERT INTO race (Nom) VALUES ('Trotteur');
INSERT INTO `Personne`(`ID`, `Prenom`, `Nom`, `Mail`, `Telephone`, `DateNaissance`, `NbHeureActiviteMaxSemaine`, `Discriminator`, `Password`) VALUES (1, 'Eleonore', 'W', 'eleo@mail.ca', '418-505-050', 19960312, null, 'javabeans.Client', "");
INSERT INTO `Personne`(`ID`, `Prenom`, `Nom`, `Mail`, `Telephone`, `DateNaissance`, `NbHeureActiviteMaxSemaine`, `Discriminator`, `Password`) VALUES (2, 'Guillaume', 'B', 'guigui@mail.ca', '418-456-123', 19970608, null, 'javabeans.Client', "");
INSERT INTO `Personne`(`ID`, `Prenom`, `Nom`, `Mail`, `Telephone`, `DateNaissance`, `NbHeureActiviteMaxSemaine`, `Discriminator`, `Password`) VALUES (3, 'Mathieu', 'S', 'poney4ever@mail.ca', '+33608956830', 19650602, 20, 'javabeans.Professeur', "");
INSERT INTO `Personne`(`ID`, `Prenom`, `Nom`, `Mail`, `Telephone`, `DateNaissance`, `NbHeureActiviteMaxSemaine`, `Discriminator`, `Password`) VALUES (4, 'Madeleine', 'S', 'madeleine@mail.ca', '418-789-456', 19800615, null, 'javabeans.Administrateur', "");
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (1, 'Pré Ouest', 4, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (2, 'Pré Nord', 2, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (3, 'Pré-Jean', 4, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (4, 'Manège A', 8, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (5, 'Manège B', 6, "Priorité aux poneys");
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (6, 'Forêt Secteur Ouest', 5, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (7, 'Forêt Secteur Nord', 7, null);
INSERT INTO `Lieu`(`ID`, `Nom`, `Capacite`, `Description`) VALUES (8, 'Rivière', 6, null);
INSERT INTO `Activite`(`ID`, `LieuID`, `PersonneID`, `TypeID`, `Nom`, `Commentaire`, `Details`, `Date`, `Duree`, `Capacite`, `EstActive`) VALUES (1, 8, 3, 2, 'Promenade au bord de l''eau', 'Tout c''est bien passé', 'RDV au centre equestre', 20190105, 5, 4, true);
INSERT INTO `Activite`(`ID`, `LieuID`, `PersonneID`, `TypeID`, `Nom`, `Commentaire`, `Details`, `Date`, `Duree`, `Capacite`, `EstActive`) VALUES (2, 6, 3, 1, 'Randonnée en forêt', '', 'Prévoir un K-Way', 20180403, 4, 3, true);
INSERT INTO `Activite`(`ID`, `LieuID`, `PersonneID`, `TypeID`, `Nom`, `Commentaire`, `Details`, `Date`, `Duree`, `Capacite`, `EstActive`) VALUES (3, 4, 3, 4, 'Cours pour galop 5', '', 'Prevoir le matériel necessaire', 20190925, 6, 10, true);
INSERT INTO `Reservation`(`Date`, `NbPersonne`, `EstActive`, `PersonneID`, `ActiviteID`) VALUES (20180303, 2, true, 1, 2);
INSERT INTO `Reservation`(`Date`, `NbPersonne`, `EstActive`, `PersonneID`, `ActiviteID`) VALUES (20180306, 1, true, 2, 2);
INSERT INTO `Reservation`(`Date`, `NbPersonne`, `EstActive`, `PersonneID`, `ActiviteID`) VALUES (20181253, 1, true, 1, 1);
INSERT INTO `Reservation`(`Date`, `NbPersonne`, `EstActive`, `PersonneID`, `ActiviteID`) VALUES (20190306, 1, true, 2, 3);
INSERT INTO `Cheval`(`ID`, `PersonneID`, `RaceID`, `Nom`, `DateNaissance`, `Description`, `Commentaire`, `NbHeureMaxSemaine`, `Taille`) VALUES (1, 2, 2, 'Crêpe', 20150306, 'Aime le sucre', 'Boiteux', 6, 160);
INSERT INTO `Cheval`(`ID`, `PersonneID`, `RaceID`, `Nom`, `DateNaissance`, `Description`, `Commentaire`, `NbHeureMaxSemaine`, `Taille`) VALUES (2, 1, 1, 'Brownie', 20120923, 'Aime les carottes', 'Aimable', 5, 170);
INSERT INTO `Cheval`(`ID`, `PersonneID`, `RaceID`, `Nom`, `DateNaissance`, `Description`, `Commentaire`, `NbHeureMaxSemaine`, `Taille`) VALUES (3, 2, 3, 'Cookie', 20110303, 'Aime les graines', '', 15, 175);
INSERT INTO `Cheval`(`ID`, `PersonneID`, `RaceID`, `Nom`, `DateNaissance`, `Description`, `Commentaire`, `NbHeureMaxSemaine`, `Taille`) VALUES (4, 2, 4, 'Pepito', 20121212, 'Aime la viande', '', 15, 165);
INSERT INTO `Cheval_Activite`(`ChevalID`, `ActiviteID`) VALUES (1, 1);
INSERT INTO `Cheval_Activite`(`ChevalID`, `ActiviteID`) VALUES (2, 1);
INSERT INTO `Cheval_Activite`(`ChevalID`, `ActiviteID`) VALUES (3, 1);


