ALTER TABLE `Activite` DROP FOREIGN KEY `TypeActivite`;
ALTER TABLE `Cheval` DROP FOREIGN KEY `FKCheval119774`;
ALTER TABLE `Reservation` DROP FOREIGN KEY `Reservation`;
ALTER TABLE `Reservation` DROP FOREIGN KEY `Reservation2`;
ALTER TABLE `Activite` DROP FOREIGN KEY `FKActivite394526`;
ALTER TABLE `Activite` DROP FOREIGN KEY `FKActivite957273`;
ALTER TABLE `Cheval_Activite` DROP FOREIGN KEY `ActiviteCheval`;
ALTER TABLE `Cheval_Activite` DROP FOREIGN KEY `ActiviteCheval2`;
ALTER TABLE `Cheval` DROP FOREIGN KEY `FKCheval74102`;
DROP TABLE IF EXISTS `Type`;
DROP TABLE IF EXISTS `Race`;
DROP TABLE IF EXISTS `Personne`;
DROP TABLE IF EXISTS `Lieu`;
DROP TABLE IF EXISTS `Activite`;
DROP TABLE IF EXISTS `Reservation`;
DROP TABLE IF EXISTS `Cheval`;
DROP TABLE IF EXISTS `Cheval_Activite`;
CREATE TABLE `Type` (`ID` int(10) NOT NULL AUTO_INCREMENT, `Nom` varchar(255), `Description` varchar(255), PRIMARY KEY (`ID`), CONSTRAINT `TypeNomUnique` UNIQUE (`Nom`));
CREATE TABLE `Race` (`ID` int(10) NOT NULL AUTO_INCREMENT, `Nom` varchar(255), PRIMARY KEY (`ID`), CONSTRAINT `RaceNomUnique` UNIQUE (`Nom`));
CREATE TABLE `Personne` (`ID` int(10) NOT NULL AUTO_INCREMENT, `Prenom` varchar(255), `Nom` varchar(255), `Mail` varchar(255), `Telephone` varchar(255), `DateNaissance` int(10) NOT NULL, `NbHeureActiviteMaxSemaine` int(10), `Discriminator` varchar(255) NOT NULL, `Password` varchar(255), PRIMARY KEY (`ID`), CONSTRAINT `PersonneMailUnique` UNIQUE (`Mail`));
CREATE TABLE `Lieu` (`ID` int(10) NOT NULL AUTO_INCREMENT, `Nom` varchar(255), `Capacite` int(10) NOT NULL, `Description` varchar(255), PRIMARY KEY (`ID`), CONSTRAINT `LieuNomUnique` UNIQUE (`Nom`));
CREATE TABLE `Activite` (`ID` int(10) NOT NULL AUTO_INCREMENT, `LieuID` int(10) NOT NULL, `PersonneID` int(10) NOT NULL, `TypeID` int(10) NOT NULL, `Nom` varchar(255), `Commentaire` varchar(255), `Details` varchar(255), `Date` int(10) NOT NULL, `Duree` float NOT NULL, `Capacite` int(10) NOT NULL, `EstActive` tinyint(1) NOT NULL, PRIMARY KEY (`ID`));
CREATE TABLE `Reservation` (`ID` int(10) NOT NULL AUTO_INCREMENT, `Date` int(10) NOT NULL, `NbPersonne` int(10) NOT NULL, `EstActive` tinyint(1) NOT NULL, `PersonneID` int(10) NOT NULL, `ActiviteID` int(10) NOT NULL, PRIMARY KEY (`ID`));
CREATE TABLE `Cheval` (`ID` int(10) NOT NULL AUTO_INCREMENT, `PersonneID` int(10) NOT NULL, `RaceID` int(10) NOT NULL, `Nom` varchar(255) NOT NULL, `DateNaissance` int(10) NOT NULL, `Description` varchar(255), `Commentaire` varchar(255), `NbHeureMaxSemaine` int(10) NOT NULL, `Taille` int(10) NOT NULL, PRIMARY KEY (`ID`), CONSTRAINT `NomChevalUnique` UNIQUE (`Nom`));
CREATE TABLE `Cheval_Activite` (`ChevalID` int(10) NOT NULL, `ActiviteID` int(10) NOT NULL, PRIMARY KEY (`ChevalID`, `ActiviteID`));
ALTER TABLE `Activite` ADD CONSTRAINT `TypeActivite` FOREIGN KEY (`TypeID`) REFERENCES `Type` (`ID`);
ALTER TABLE `Cheval` ADD CONSTRAINT `FKCheval119774` FOREIGN KEY (`RaceID`) REFERENCES `Race` (`ID`);
ALTER TABLE `Reservation` ADD CONSTRAINT `Reservation` FOREIGN KEY (`PersonneID`) REFERENCES `Personne` (`ID`);
ALTER TABLE `Reservation` ADD CONSTRAINT `Reservation2` FOREIGN KEY (`ActiviteID`) REFERENCES `Activite` (`ID`);
ALTER TABLE `Activite` ADD CONSTRAINT `FKActivite394526` FOREIGN KEY (`PersonneID`) REFERENCES `Personne` (`ID`);
ALTER TABLE `Activite` ADD CONSTRAINT `FKActivite957273` FOREIGN KEY (`LieuID`) REFERENCES `Lieu` (`ID`);
ALTER TABLE `Cheval_Activite` ADD CONSTRAINT `ActiviteCheval` FOREIGN KEY (`ChevalID`) REFERENCES `Cheval` (`ID`);
ALTER TABLE `Cheval_Activite` ADD CONSTRAINT `ActiviteCheval2` FOREIGN KEY (`ActiviteID`) REFERENCES `Activite` (`ID`);
ALTER TABLE `Cheval` ADD CONSTRAINT `FKCheval74102` FOREIGN KEY (`PersonneID`) REFERENCES `Personne` (`ID`);